---
global:
  pattern: regional-resiliency-pattern

  cicd:
    namespace: devsecops-ci

  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

  secure-registry:
    namespace: "openshift-storage"

  imageregistry:
    account: PLAINTEXT
    hostname: quay.io
    type: quay

  git:
    hostname: github.com
    account: PLAINTEXT
    username: PLAINTEXT
    email: SOMEWHERE@EXAMPLE.COM
    dev_revision: main

  quay:
    # Needs to be set consistently between hub and spoke clusters
    # TODO: Move back to the hub chart, store in a configmap, have an ACM policy distribute to spoke clusters, have spoke look up from configmap
    org:
      name: devel
      email: devel@myorg.com
    repo: example
  opp: false

main:
  clusterGroupName: hub

regionalDR:
  - name: resilient # Matches with ClusterSet
    globalnetEnabled: false # Support for overlapping CIDR
    clusters: # Pair of clusters, make sure to create each in a different region
      primary:
        name: ocp-primary
        version: 4.16.8
        # See OpenShift documentation for install config spec
        # https://docs.openshift.com/container-platform/4.14/installing/installing_aws/installing-aws-customizations.html
        install_config:
          apiVersion: v1
          metadata:
            name: ocp-primary
          baseDomain: sandbox847.opentlc.com
          controlPlane:
            name: master
            replicas: 3
            platform:
              aws:
                type: m5.2xlarge
                zones:
                  - eu-west-1a
          compute:
            - name: worker
              replicas: 6
              platform:
                aws:
                  type: m5.2xlarge
                  zones:
                    - eu-west-1a
          networking:
            clusterNetwork:
              - cidr: 10.128.0.0/14
                hostPrefix: 23
            machineNetwork:
              - cidr: 10.0.0.0/16
            networkType: OVNKubernetes
            serviceNetwork:
              - 172.30.0.0/16
          platform:
            aws:
              region: eu-west-1
              userTags:
                project: ValidatedPatterns

          publish: External
          sshKey: ""
          pullSecret: ""
      secondary:
        name: ocp-secondary
        version: 4.16.8
        install_config:
          apiVersion: v1
          metadata:
            name: ocp-secondary
          baseDomain: sandbox847.opentlc.com
          controlPlane:
            name: master
            replicas: 3
            platform:
              aws:
                type: m5.2xlarge
                zones:
                  - eu-north-1a
          compute:
            - name: worker
              replicas: 6
              platform:
                aws:
                  type: m5.2xlarge
                  zones:
                    - eu-north-1a
          networking:
            clusterNetwork:
              - cidr: 10.132.0.0/14
                hostPrefix: 23
            machineNetwork:
              - cidr: 10.1.0.0/16
            networkType: OVNKubernetes
            serviceNetwork:
              - 172.31.0.0/16
          platform:
            aws:
              region: eu-north-1
              userTags:
                project: ValidatedPatterns

          publish: External
          sshKey: ""
          pullSecret: ""
    # List of sync policy intervals: RPO should be larger than the sync time.
    # If your sync process takes 3 mins, the interval should be at least 4-5 mins.
    intervals:
      - 2m
      - 5m
